export { Shell } from './components/Shell'
export { ShellProvider, ShellContext, useShellExtensions } from './components/ShellProvider'
export { ActivityRail } from './components/ActivityRail'
export { TabBar } from './components/TabBar'
export { Sidebar } from './components/Sidebar'
export { Canvas } from './components/Canvas'
export { RightSidebar } from './components/RightSidebar'
export { Panel } from './components/Panel'
export { StatusBar } from './components/StatusBar'
export { CommandPalette } from './components/CommandPalette'
export { ExtensionErrorBoundary } from './extension/ExtensionErrorBoundary'
export { useShell } from './extension/useShell'
export { useExtensionStore } from './extension/useExtensionStore'
export { useShellStore } from './store/shell-store'
export * from './types'
