export { ActivityRail } from './components/ActivityRail'
export { TabBar } from './components/TabBar'
export { Sidebar } from './components/Sidebar'
export { Canvas } from './components/Canvas'
export { RightSidebar } from './components/RightSidebar'
export { Panel } from './components/Panel'
export { StatusBar } from './components/StatusBar'
export { CommandPalette } from './components/CommandPalette'
export * from './types'
